#!/usr/bin/env bash
# fleet:init / fleet:apply — config-repo support, following the Gradle-wrapper
# pattern: a fleet config repo holds DATA (repos.txt, runner-mesh.version,
# values/) plus a ~20-line shim whose only job is to fetch the engine at the
# pinned ref and delegate here. All real logic stays in this versioned
# engine, so config repos never need upstream fixes.
# Intended to be sourced, not executed.

rm::fleet::_parse_repos() {
  # Prints one owner/repo per line from a repos.txt, stripping comments,
  # whitespace, and blank lines.
  local file="$1" line
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%#*}"
    line="$(printf '%s' "${line}" | tr -d '[:space:]')"
    [[ -n "${line}" ]] && printf '%s\n' "${line}"
  done < "${file}"
}

# fleet:apply [config-dir] [--prune] — converge the cluster on the config
# repo's declared state: sync committed value overrides, ensure the
# controller, provision every repo in repos.txt. With --prune, also remove
# scale-sets that are no longer listed (never the default: prune deletes
# infrastructure, so it stays opt-in per invocation).
rm::fleet::apply() {
  local config_dir="" prune=0 arg
  for arg in "$@"; do
    case "${arg}" in
      --prune) prune=1 ;;
      -*) rm::die "unknown flag: ${arg}" ;;
      *) config_dir="${arg}" ;;
    esac
  done
  config_dir="${config_dir:-.}"
  config_dir="$(cd "${config_dir}" && pwd)" || rm::die "config dir not found"
  [[ -f "${config_dir}/repos.txt" ]] \
    || rm::die "no repos.txt in ${config_dir} — is this a fleet config repo? (see 'runner-mesh fleet:init')"

  rm::preflight::run || rm::die "fix the failed checks above, then re-run"
  rm::github_app::require_config

  # Committed per-repo overrides are the fleet's source of truth — sync
  # them into the local dir repos:add reads from, so every machine
  # converges on the same config.
  local f synced=0
  mkdir -p "${RM_REPOS_STATE_DIR}"
  for f in "${config_dir}"/values/*.values.yaml; do
    [[ -e "${f}" ]] || continue
    cp "${f}" "${RM_REPOS_STATE_DIR}/$(basename "${f}")"
    synced=$((synced + 1))
  done
  rm::info "synced ${synced} committed value override(s) from values/"

  rm::cluster::install

  local -a repos=()
  local repo
  while IFS= read -r repo; do
    repos+=("${repo}")
  done < <(rm::fleet::_parse_repos "${config_dir}/repos.txt")

  if [[ ${#repos[@]} -eq 0 ]]; then
    rm::warn "repos.txt lists no repos — nothing to provision"
  else
    rm::repos::add "${repos[@]}"
  fi

  if [[ "${prune}" == "1" ]]; then
    rm::fleet::_prune "${repos[@]+"${repos[@]}"}"
  fi

  rm::log "Fleet converged. Current state:"
  rm::status::run
}

# Remove provisioned scale-sets whose repo is no longer in repos.txt.
# A release name is a slug (owner-repo, lowercased) — ambiguous to reverse
# — so the original owner/repo is recovered from the githubConfigUrl in the
# per-repo values file repos:add generated.
rm::fleet::_prune() {
  local -a keep_slugs=()
  local repo
  for repo in "$@"; do
    keep_slugs+=("$(rm::repos::_slug "${repo}")")
  done

  local releases ns release slug keep url
  releases="$(helm list --all-namespaces -o json 2>/dev/null \
    | jq -r '.[] | select(.namespace == "arc-runners" or (.namespace | startswith("arc-runners-"))) | "\(.namespace)\t\(.name)"')"

  while IFS=$'\t' read -r ns release; do
    [[ -z "${release}" ]] && continue
    keep=0
    for slug in "${keep_slugs[@]+"${keep_slugs[@]}"}"; do
      [[ "${release}" == "${slug}" ]] && { keep=1; break; }
    done
    [[ "${keep}" == "1" ]] && continue

    url="$(grep -E '^githubConfigUrl:' "${RM_REPOS_STATE_DIR}/${release}.values.yaml" 2>/dev/null \
      | sed -E 's|^githubConfigUrl:[[:space:]]*"?https://github.com/([^"]+)"?.*|\1|')"
    if [[ -z "${url}" ]]; then
      rm::warn "prune: cannot resolve '${ns}/${release}' back to owner/repo (no local values file) — remove manually with repos:remove"
      continue
    fi
    rm::log "prune: ${url} is provisioned but not in repos.txt"
    rm::repos::remove "${url}"
  done <<<"${releases}"
}

# fleet:init [dir] — scaffold a new fleet config repo: data files plus the
# delegating shim. Generated by the engine so shim and engine can't drift.
rm::fleet::init() {
  local dir="${1:-.}"
  mkdir -p "${dir}/values"
  dir="$(cd "${dir}" && pwd)"

  local clobber=""
  for f in bootstrap.sh repos.txt runner-mesh.version; do
    [[ -e "${dir}/${f}" ]] && clobber="${clobber} ${f}"
  done
  if [[ -n "${clobber}" ]]; then
    rm::confirm "This will overwrite:${clobber}. Continue?" || rm::die "aborted"
  fi

  local engine_ref engine_url
  engine_ref="$(git -C "${RM_ROOT}" rev-parse HEAD 2>/dev/null || echo main)"
  engine_url="$(git -C "${RM_ROOT}" remote get-url origin 2>/dev/null || echo 'https://github.com/eilst/runner-mesh.git')"

  printf '%s\n' "${engine_ref}" > "${dir}/runner-mesh.version"

  cat > "${dir}/repos.txt" <<'EOF'
# One owner/repo per line. Lines starting with # are ignored.
# The GitHub App must already be installed on each repo listed here
# (GitHub → Settings → Applications → your app → Configure).
#
# example-org/example-repo
EOF

  cat > "${dir}/.gitignore" <<'EOF'
.runner-mesh/
*.pem
*.key
.env
.DS_Store
EOF

  cat > "${dir}/values/README.md" <<'EOF'
# Per-repo value overrides

Optional. One file per repo, named `<owner>-<repo>.values.yaml`
(lowercase, `/` → `-`). `./bootstrap.sh` syncs these before
provisioning, so the overrides committed here are what every machine
converges on. Fleet-wide defaults live in the engine:
`.runner-mesh/charts/values/scale-set.defaults.yaml`.
EOF

  # The shim: the only executable code a fleet repo carries. Fetches the
  # engine at the pinned ref, then delegates everything to fleet:apply.
  cat > "${dir}/bootstrap.sh" <<EOF
#!/usr/bin/env bash
# runner-mesh wrapper shim — fetches the pinned engine and delegates.
# All logic lives in the engine; keep this file boring and stable.
set -euo pipefail
HERE="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
ENGINE="\${HERE}/.runner-mesh"
REPO="\${RUNNER_MESH_REPO:-${engine_url}}"
REF="\$(tr -d '[:space:]' < "\${HERE}/runner-mesh.version")"
[[ -d "\${ENGINE}/.git" ]] || git clone --quiet "\${REPO}" "\${ENGINE}"
git -C "\${ENGINE}" fetch --quiet --tags origin
git -C "\${ENGINE}" checkout --quiet "\${REF}"
if git -C "\${ENGINE}" symbolic-ref -q HEAD >/dev/null; then
  git -C "\${ENGINE}" pull --quiet --ff-only origin "\${REF}"
fi
exec "\${ENGINE}/bin/runner-mesh" fleet:apply "\${HERE}" "\$@"
EOF
  chmod +x "${dir}/bootstrap.sh"

  cat > "${dir}/README.md" <<'EOF'
# Fleet config for runner-mesh

Data-only config repo (plus a small delegating shim) for
[runner-mesh](https://github.com/eilst/runner-mesh). Keep it **private**
— it names your repos and machines. It must never hold credentials.

| File | Purpose |
|---|---|
| `repos.txt` | Repos to provision, one `owner/repo` per line |
| `runner-mesh.version` | Engine git ref (tag/branch/commit) — bump to upgrade |
| `values/` | Committed per-repo overrides, synced on every apply |
| `bootstrap.sh` | Shim: fetch pinned engine → `runner-mesh fleet:apply` |

## Any machine, any time (idempotent)

```bash
./bootstrap.sh            # converge this machine on the declared state
./bootstrap.sh --prune    # also remove scale-sets no longer in repos.txt
```

One-time per fleet: `./.runner-mesh/bin/runner-mesh app:init` on your
first machine. Additional machines need `~/.config/runner-mesh/github-app.json`
copied over a secure channel — deliberately never committed.
EOF

  rm::ok "fleet config scaffolded in ${dir} (engine pinned to ${engine_ref})"
  rm::info "edit repos.txt, commit to a private repo, then run ./bootstrap.sh"
}
