#!/usr/bin/env bash
# fleet:gitops — generate a Flux CD layout inside a fleet config repo, so
# the cluster reconciles itself from git instead of waiting for an
# operator machine to run `make apply`.
#
# Everything emitted here is GENERATED from the same sources of truth the
# imperative path uses (repos.txt, values/, the engine's chart defaults):
# re-run `fleet:gitops` after editing repos.txt to regenerate. Files the
# operator owns (values/*.values.yaml) are referenced, never rewritten.
#
# Layout written into the fleet repo:
#   kustomization.yaml            root kustomization (resources + values
#                                 ConfigMap generators, sops-aware)
#   flux/namespaces.yaml          arc-systems + arc-runners
#   flux/controller.yaml          HelmRepository (OCI) + controller HelmRelease
#   flux/pools/<slug>.yaml        one HelmRelease per repos.txt entry
#   flux/secrets/github-config.enc.yaml
#                                 SOPS-encrypted Secrets (App credentials,
#                                 one per pool, in arc-runners)
#   flux/sync.yaml                the Flux Kustomization CR (applied once
#                                 at bootstrap; from then on git drives)
#   flux/defaults/                copies of the engine's chart defaults
#                                 this generation used (pinned, visible)
#
# Intended to be sourced, not executed.

RM_ARC_CHART_VERSION="${RM_ARC_CHART_VERSION:-0.14.2}"
RM_GITOPS_MARKER="# GENERATED by 'runner-mesh fleet:gitops' — regenerate, don't hand-edit."

rm::gitops::_installation_id() {
  # Same resolution order as repos:add, plus a fallback that reads the id
  # out of an existing in-cluster secret — useful when the GitHub API is
  # unreachable but the fleet is already provisioned.
  if [[ -n "${RM_INSTALLATION_ID:-}" ]]; then
    printf '%s\n' "${RM_INSTALLATION_ID}"
    return 0
  fi
  local from_cluster
  from_cluster="$(kubectl -n arc-runners get secrets -o json 2>/dev/null \
    | jq -r '[.items[] | select(.metadata.name | startswith("github-config-secret-")) | .data.github_app_installation_id][0] // empty' \
    | base64 -d 2>/dev/null)"
  if [[ -n "${from_cluster}" ]]; then
    printf '%s\n' "${from_cluster}"
    return 0
  fi
  rm::repos::_installation_id
}

rm::gitops::scaffold() {
  local dir="${1:-.}"
  command -v sops >/dev/null 2>&1 || rm::die "sops is required (brew install sops)"
  command -v age-keygen >/dev/null 2>&1 || rm::die "age is required (brew install age)"
  rm::github_app::require_config
  [[ -f "${dir}/repos.txt" ]] || rm::die "${dir} doesn't look like a fleet config repo (no repos.txt)"
  [[ -f "${RM_AGE_KEY_FILE}" ]] || rm::die "no age key at ${RM_AGE_KEY_FILE} — run 'fleet:seal' once first"
  dir="$(cd "${dir}" && pwd)"

  local pubkey app_id installation_id engine_root
  pubkey="$(age-keygen -y "${RM_AGE_KEY_FILE}")"
  app_id="$(jq -r .app_id "${RM_APP_CONFIG}")"
  installation_id="$(rm::gitops::_installation_id)"
  engine_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

  mkdir -p "${dir}/flux/pools" "${dir}/flux/secrets" "${dir}/flux/defaults"

  # Chart defaults travel with the fleet repo so Flux (which never sees
  # the engine checkout) can layer them under each pool's own values.
  cp "${engine_root}/charts/values/controller.values.yaml" "${dir}/flux/defaults/controller.values.yaml"
  cp "${engine_root}/charts/values/scale-set.defaults.yaml" "${dir}/flux/defaults/scale-set.defaults.yaml"

  cat > "${dir}/flux/namespaces.yaml" <<EOF
${RM_GITOPS_MARKER}
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
EOF

  cat > "${dir}/flux/controller.yaml" <<EOF
${RM_GITOPS_MARKER}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: arc-charts
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: arc-systems
  storageNamespace: arc-systems
  releaseName: arc
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: "${RM_ARC_CHART_VERSION}"
      sourceRef:
        kind: HelmRepository
        name: arc-charts
  valuesFrom:
    - kind: ConfigMap
      name: rm-controller-values
      valuesKey: values.yaml
EOF

  # Root kustomization: resources + a values ConfigMap per pool so edits
  # to values/*.values.yaml flow straight into the HelmReleases.
  local kustomization="${dir}/kustomization.yaml"
  cat > "${kustomization}" <<EOF
${RM_GITOPS_MARKER}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux/namespaces.yaml
  - flux/controller.yaml
  - flux/secrets/github-config.enc.yaml
EOF

  local repo slug values_rel
  local -a slugs=()
  while IFS= read -r repo; do
    slug="$(rm::repos::_slug "${repo}")"
    slugs+=("${slug}")
    values_rel="values/${slug}.values.yaml"
    [[ -f "${dir}/${values_rel}" ]] \
      || rm::warn "${values_rel} not found — pool '${slug}' will deploy with engine defaults only"

    cat > "${dir}/flux/pools/${slug}.yaml" <<EOF
${RM_GITOPS_MARKER}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${slug}
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: arc-runners
  storageNamespace: arc-runners
  releaseName: ${slug}
  dependsOn:
    - name: arc
  chart:
    spec:
      chart: gha-runner-scale-set
      version: "${RM_ARC_CHART_VERSION}"
      sourceRef:
        kind: HelmRepository
        name: arc-charts
  valuesFrom:
    - kind: ConfigMap
      name: rm-scale-set-defaults
      valuesKey: values.yaml
    - kind: ConfigMap
      name: rm-${slug}-values
      valuesKey: values.yaml
      optional: true
EOF
    printf '  - flux/pools/%s.yaml\n' "${slug}" >> "${kustomization}"
  done < <(rm::fleet::_parse_repos "${dir}/repos.txt")

  cat >> "${kustomization}" <<EOF

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: rm-controller-values
    namespace: flux-system
    files:
      - values.yaml=flux/defaults/controller.values.yaml
  - name: rm-scale-set-defaults
    namespace: flux-system
    files:
      - values.yaml=flux/defaults/scale-set.defaults.yaml
EOF
  local s
  for s in "${slugs[@]}"; do
    if [[ -f "${dir}/values/${s}.values.yaml" ]]; then
      cat >> "${kustomization}" <<EOF
  - name: rm-${s}-values
    namespace: flux-system
    files:
      - values.yaml=values/${s}.values.yaml
EOF
    fi
  done

  # GitHub App credential secrets, one per pool, SOPS-encrypted so they
  # can live in git. Flux's kustomize-controller decrypts with the age
  # key held in the cluster (secret 'sops-age' in flux-system).
  local plain enc key_file
  plain="$(rm::mktemp_suffixed rm-gitops-secret .yaml)"
  key_file="$(rm::mktemp_suffixed rm-gitops-key .pem)"
  jq -r .private_key "${RM_APP_CONFIG}" > "${key_file}"
  : > "${plain}"
  local first=1
  for s in "${slugs[@]}"; do
    if [[ "${first}" == "1" ]]; then first=0; else printf -- '---\n' >> "${plain}"; fi
    kubectl create secret generic "github-config-secret-${s}" \
      --namespace arc-runners \
      --from-literal=github_app_id="${app_id}" \
      --from-literal=github_app_installation_id="${installation_id}" \
      --from-file=github_app_private_key="${key_file}" \
      --dry-run=client -o yaml >> "${plain}"
  done
  rm -f "${key_file}"
  enc="${dir}/flux/secrets/github-config.enc.yaml"
  sops --encrypt --age "${pubkey}" --encrypted-regex '^(data|stringData)$' \
    --input-type yaml --output-type yaml "${plain}" > "${enc}" \
    || { rm -f "${plain}"; rm::die "sops encryption of the App secrets failed"; }
  rm -f "${plain}"

  cat > "${dir}/flux/sync.yaml" <<EOF
${RM_GITOPS_MARKER}
# Apply this ONCE after 'flux bootstrap' (see docs/gitops-flux.md); from
# then on, every push to this repo reconciles the cluster automatically.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: runner-mesh-fleet
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  path: ./
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
EOF

  rm::ok "GitOps layout generated under ${dir} (${#slugs[@]} pool(s), chart ${RM_ARC_CHART_VERSION})"
  rm::log "next steps (one-time, see docs/gitops-flux.md for detail):"
  rm::info "1. flux bootstrap github --owner <you> --repository <this-repo> --personal --path flux-system"
  rm::info "2. kubectl -n flux-system create secret generic sops-age --from-file=age.agekey=${RM_AGE_KEY_FILE}"
  rm::info "3. git add -A && git commit -m 'gitops: flux layout' && git push"
  rm::info "4. kubectl apply -f flux/sync.yaml"
  rm::info "then: flux get helmreleases -n flux-system --watch"
}
