#!/usr/bin/env bash
# repos:migrate — rewrite workflows' runs-on targets to scale-set names,
# per an EXPLICIT mapping (never inferred: whether '[self-hosted, linux]'
# may move to an arm64 pool is a judgment about the workloads, not
# something a tool should guess). Optionally commits the change to a new
# branch and opens a draft PR for review — it never pushes to the default
# branch.
# Intended to be sourced, not executed.

# rm::migrate::_rewrite <wf_dir> <map...> — mapN is 'labels=target' where
# labels is the comma-separated array content (order/spacing/case
# insensitive). Prints "changed <n> line(s)" style output; python3 is
# already a preflight-required dependency.
rm::migrate::_rewrite() {
  local wf_dir="$1"; shift
  python3 - "${wf_dir}" "$@" <<'PYEOF'
import re
import sys
from pathlib import Path

wf_dir = Path(sys.argv[1])
mappings = {}
for arg in sys.argv[2:]:
    labels, _, target = arg.partition("=")
    key = frozenset(l.strip().lower() for l in labels.split(",") if l.strip())
    mappings[key] = target.strip()

pattern = re.compile(r"^(\s*runs-on:\s*)\[([^\]]*)\](\s*(?:#.*)?)$")
total = 0
for path in sorted(wf_dir.glob("*.y*ml")):
    lines = path.read_text().splitlines(keepends=True)
    changed = 0
    out = []
    for line in lines:
        m = pattern.match(line.rstrip("\n"))
        if m:
            key = frozenset(
                l.strip().strip("'\"").lower()
                for l in m.group(2).split(",") if l.strip()
            )
            if key in mappings:
                out.append(f"{m.group(1)}{mappings[key]}{m.group(3)}\n")
                changed += 1
                continue
        out.append(line)
    if changed:
        path.write_text("".join(out))
        print(f"  {path.name}: {changed} line(s) rewritten")
        total += changed
print(f"total: {total}")
PYEOF
}

rm::migrate::run() {
  local path="" branch="runner-mesh/migrate-runs-on" make_pr=0
  local -a maps=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --map)    maps+=("$2"); shift 2 ;;
      --branch) branch="$2"; shift 2 ;;
      --pr)     make_pr=1; shift ;;
      -*)       rm::die "unknown flag: $1" ;;
      *)        path="$1"; shift ;;
    esac
  done
  path="${path:-.}"
  [[ ${#maps[@]} -gt 0 ]] \
    || rm::die "usage: runner-mesh repos:migrate <path> --map 'labels=scale-set-name' [--map ...] [--branch NAME] [--pr]"
  local wf_dir="${path}/.github/workflows"
  [[ -d "${wf_dir}" ]] || rm::die "no workflows at ${wf_dir}"

  if [[ "${make_pr}" == "1" ]]; then
    [[ -z "$(git -C "${path}" status --porcelain)" ]] \
      || rm::die "working tree at ${path} is not clean — commit or stash first"
    git -C "${path}" checkout -b "${branch}" \
      || rm::die "could not create branch '${branch}' (does it already exist?)"
  fi

  rm::log "Rewriting runs-on targets in ${wf_dir}"
  rm::migrate::_rewrite "${wf_dir}" "${maps[@]}"

  if [[ "${make_pr}" == "1" ]]; then
    if [[ -z "$(git -C "${path}" status --porcelain)" ]]; then
      git -C "${path}" checkout - >/dev/null
      git -C "${path}" branch -d "${branch}" >/dev/null
      rm::warn "no lines matched any --map — nothing to PR"
      return 0
    fi
    git -C "${path}" add .github/workflows
    git -C "${path}" commit -q -m "ci: migrate runs-on label arrays to runner-mesh scale-set names

Scale-set runners match by name only; these jobs' label arrays could
never reach them. Rewritten per an explicit mapping via
'runner-mesh repos:migrate' — unmapped targets (arch- or OS-constrained)
left untouched."
    git -C "${path}" push -q -u origin "${branch}"
    gh pr create --repo "$(git -C "${path}" remote get-url origin | sed -E 's|.*github.com[:/]||; s|\.git$||')" \
      --head "${branch}" --draft \
      --title "ci: migrate runs-on to runner-mesh scale-set names" \
      --body "$(rm::migrate::_pr_body "${maps[@]}")"
    rm::ok "draft PR opened from '${branch}' — review the diff before marking ready"
  else
    rm::ok "files rewritten in place (no branch/PR requested) — review with 'git diff'"
  fi
}

rm::migrate::_pr_body() {
  local m map_lines=""
  for m in "$@"; do
    map_lines+="- \`[${m%%=*}]\` → \`${m#*=}\`"$'\n'
  done
  cat <<EOF
Rewrites \`runs-on\` label arrays to runner-mesh scale-set names, per this explicit mapping:

${map_lines}
**Why**: ARC scale-set runners match by name only — GitHub removed label
routing for them — so these jobs could never reach the new runner pool.

**Deliberately not migrated**: any target not in the mapping above
(e.g. x64- or macOS-constrained jobs on an arm64-only cluster).

**Rollout**: classic runners and scale-sets coexist without conflict;
merging this shifts only the mapped jobs. Generated by
\`runner-mesh repos:migrate\`; the rewrite is mechanical, the mapping
was chosen by a human.
EOF
}
